### PR TITLE
Cleanup files

### PR DESCRIPTION
**Pull request by Xorboo**
Setup `.gitignore` and cleanup files that should not be pushed to version control.

Basically using standard Unity's `.gitignore` with slight modification to keep Wwise files. Also, remove its `.backup` and `.cache` folders

### CODE REVIEW

**Comment by alxtrkhv** [comment]
@Xorboo well done!
you were way faster than me with the cleanup ;)

however, it's a pity there is no official or any other well established .gitignore template for wwise

I'd like to suggest adding at least 

```
*.akd
*.prof
*.validationcache
*.wsettings
```

My suggestions are based on a brief search for 'gitignore wwise' over github and this super outdated thread https://www.audiokinetic.com/qa/1547/there-definitive-files-should-could-omitted-source-control

**Comment by Xorboo** [comment]
@alxtrkhv Hey, thanks for the feedback. I saw that page, but I've never worked with Wwise before and decided not to risk it in the first pass. Added those files to gitignore as well.

Also, I've kept `.pdb` files for Wwise plugin (see `Assets\Wwise\API\Runtime\Plugins\Windows\x86\Debug` and other folders nearby). Not entirely sure there is a need to debug Wwise plugin in some way, do you think we can remove them too?

**Comment by alxtrkhv** [comment]
@Xorboo Neither am I sure
Back to the days I worked with wwise I used the most generic unity gitignore with the already mentioned adjustments for wwise. And since unity gitignore includes `*.pdb`, I believe I ignored those. But since you already kept those, I see no harm.
I also strongly suggest removing (not gitignoring) `WwiseUnityIntegration_Mac_Src.zip` and `WwiseUnityIntegration_Windows_Src.zip` from the root folder. And it's all from me ;)
If no one suggests the opposite, I'd stick to the current gitignore version
Anyway we can update it later when we are more certain about some things ;)

**Comment by Xorboo** [comment]
True, seems like a thing users can install themselves if needed, done. Now its up to @ressium to merge it :)

**Pull request merged**
